In [1]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
departments = pd.read_csv(ROOT / 'data' / 'departments.csv')
employees = pd.read_csv(ROOT / 'data' / 'employees.csv')

display(departments)
display(employees.head())

  department   head  budget
0      Sales  Meena  200000
1         HR   John  150000
2         IT  David  300000
3    Finance  Priya  180000
4  Marketing  Anita  100000

  employee_id   name department       city
0        E001  Aarav      Sales    Chennai
1        E002   Diya         HR    Chennai
2        E003  Kiran         IT  Bengaluru
3        E004  Meera    Finance    Chennai
4        E005  Rohan  Marketing  Hyderabad

In [2]:
print('Number of departments:', len(departments))
print('Total department budget:', departments['budget'].sum())
display(departments.sort_values('budget', ascending=False))

Number of departments: 5
Total department budget: 930000

  department   head  budget
2         IT  David  300000
0      Sales  Meena  200000
3    Finance  Priya  180000
1         HR   John  150000
4  Marketing  Anita  100000

In [3]:
%timeit departments['budget'].sum()

44.8 μs ± 5.1 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [4]:
if 'department' in employees.columns:
    display(employees.groupby('department').size().rename('employee_count'))
else:
    print('No department column in employees.csv. Columns:', employees.columns.tolist())

if 'city' in employees.columns:
    display(employees.groupby('city').size().rename('employee_count'))

department
Finance      1
HR           1
IT           2
Marketing    1
Sales        1
Name: employee_count, dtype: int64

city
Bengaluru    1
Chennai      4
Hyderabad    1
Name: employee_count, dtype: int64